fixed a bug reported by Calvin Cannon The utility jk_check seems to be unable to check jails that have a dot included anywhere in the full path to the jail.
Example:
Jail located at:
  /full/path/2/customer.name/jail  (Note the dot in "customer.name")

When I run jk_check, I get the following errors:
  ERROR: cannot lstat() /full/path/2/customer/ !
  ERROR: cannot lstat() /full/path/2/customer !
  cannot check files in /full/path/2/customer/, is does not exist